[package]
name = "gps-serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "*"
nmea-parser = "0.10.0"
tzf-rs = "0.3.0"
icu_timezone = "1.1.0"
dtg = "5.0.0"
chrono-tz = "0.8.1"