[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]
runner = 'probe-run'

[build]
target = "thumbv7em-none-eabihf"  # Cortex-M4F (with FPU)

[env]
DEFMT_LOG = "trace"
